{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "외부 데이터: 로컬 파일, 드라이브, 스프레드시트, Cloud Storage",
      "provenance": [],
      "collapsed_sections": [],
      "toc_visible": true,
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/SunghoonSeok/Study/blob/master/test/dirty_mnist2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "7Z2jcRKwUHqV"
      },
      "source": [
        "이 노트북에서는 외부 소스의 데이터를 로드 및 저장하는 레시피를 이용할 수 있습니다."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "eikfzi8ZT_rW"
      },
      "source": [
        "# 로컬 파일 시스템"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "BaCkyg5CV5jF"
      },
      "source": [
        "## 로컬 파일 시스템의 파일 업로드\n",
        "\n",
        "<code>files.upload</code>는 업로드된 파일의 사전을 반환합니다.\n",
        "사전은 업로드된 파일 이름에 따라 키가 지정되며, 값은 업로드된 데이터를 표시합니다."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "vz-jH8T_Uk2c"
      },
      "source": [
        "from google.colab import files\n",
        "\n",
        "uploaded = files.upload()\n",
        "\n",
        "for fn in uploaded.keys():\n",
        "  print('User uploaded file \"{name}\" with length {length} bytes'.format(\n",
        "      name=fn, length=len(uploaded[fn])))"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "hauvGV4hV-Mh"
      },
      "source": [
        "## 로컬 파일 시스템으로 파일 다운로드\n",
        "\n",
        "<code>files.download</code>는 파일의 브라우저 다운로드를 로컬 컴퓨터로 호출합니다.\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "p2E4EKhCWEC5"
      },
      "source": [
        "from google.colab import files\n",
        "\n",
        "with open('example.txt', 'w') as f:\n",
        "  f.write('some content')\n",
        "\n",
        "files.download('example.txt')"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "c2W5A2px3doP"
      },
      "source": [
        "# Google Drive\n",
        "\n",
        "다음과 같은 여러 가지 방법으로 드라이브에 있는 파일에 액세스할 수 있습니다.\n",
        "- 런타임 가상 머신에 Google Drive 마운트\n",
        "- <a href=\"https://gsuitedevs.github.io/PyDrive/docs/build/html/index.html\">PyDrive</a>와 같은 API에 래퍼 사용\n",
        "- <a href=\"https://developers.google.com/drive/v3/web/about-sdk\">네이티브 REST API</a> 사용\n",
        "\n",
        "\n",
        "\n",
        "각각의 예시는 다음과 같습니다."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "u22w3BFiOveA"
      },
      "source": [
        "## 로컬에 Google Drive 마운트하기\n",
        "\n",
        "아래의 예시에서는 승인 코드를 사용해 런타임에 Google Drive를 마운트하는 방법 및 이 드라이브에서 파일을 쓰고 읽는 방법을 보여 줍니다. 이 예시를 실행하면 <a href=\"https://drive.google.com/\">https://drive.google.com/</a>에 새 파일&#40;<code>foo.txt</code>&#41;이 표시됩니다.\n",
        "\n",
        "이 방법으로는 파일을 읽고, 쓰고 이동하는 작업만 가능하므로 프로그래매틱 방식으로 공유 설정이나 기타 메타데이터를 수정하려면 아래의 다른 옵션 중 하나를 사용하세요.\n",
        "\n",
        "<strong>참고:</strong> 파일 브라우저의 '드라이브 마운트' 버튼을 사용할 때 현재 사용자만 수정한 메모장에 대해서는 인증 코드는 필요하지 않습니다."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RWSJpsyKqHjH",
        "outputId": "833ecec6-a366-4869-b757-3cfb403ce7f1"
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Mounted at /content/drive\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "G7nqvNMlV0yq"
      },
      "source": [
        "import os\r\n",
        "import numpy as np\r\n",
        "import pandas as pd\r\n",
        "\r\n",
        "train = pd.read_csv('/content/drive/My Drive/dirty_mnist_/dirty_mnist_2nd_answer.csv', index_col=None, header=0)\r\n",
        "submission = pd.read_csv('/content/drive/My Drive/dirty_mnist_/sample_submission.csv', index_col=None, header=0)\r\n",
        "\r\n",
        "\r\n",
        "import tensorflow as tf\r\n",
        "from tensorflow.keras.applications import InceptionResNetV2, InceptionV3, Xception\r\n",
        "from tensorflow.keras.models import Sequential\r\n",
        "from tensorflow.keras.layers import *\r\n",
        "\r\n",
        "model_1 = InceptionResNetV2(weights=None, include_top=True, input_shape=(256, 256, 1), classes=26)\r\n",
        "model_2 = Sequential()\r\n",
        "model_2.add(InceptionV3(weights=None, include_top=False, input_shape=(256,256,1)))\r\n",
        "model_2.add(GlobalAveragePooling2D())\r\n",
        "model_2.add(Dense(1024, kernel_initializer='he_normal', activation='relu'))\r\n",
        "model_2.add(BatchNormalization())\r\n",
        "model_2.add(Dense(512, kernel_initializer='he_normal', activation='relu'))\r\n",
        "model_2.add(BatchNormalization())\r\n",
        "model_2.add(Dense(256, kernel_initializer='he_normal', activation='relu'))\r\n",
        "model_2.add(BatchNormalization())\r\n",
        "model_2.add(Dense(10, kernel_initializer='he_normal', activation='softmax', name='predictions'))\r\n",
        "model_3 = Sequential()\r\n",
        "model_3.add(Xception(weights=None, include_top=False, input_shape=(256,256,1)))\r\n",
        "model_3.add(GlobalAveragePooling2D())\r\n",
        "model_3.add(Dense(1024, kernel_initializer='he_normal', activation='relu'))\r\n",
        "model_3.add(BatchNormalization())\r\n",
        "model_3.add(Dense(512, kernel_initializer='he_normal', activation='relu'))\r\n",
        "model_3.add(BatchNormalization())\r\n",
        "model_3.add(Dense(256, kernel_initializer='he_normal', activation='relu'))\r\n",
        "model_3.add(BatchNormalization())\r\n",
        "model_3.add(Dense(10, kernel_initializer='he_normal', activation='softmax', name='predictions'))\r\n",
        "from tensorflow.keras.optimizers import Adam\r\n",
        "optimizer1 = Adam(lr=0.002)\r\n",
        "optimizer2 = Adam(lr=0.002)\r\n",
        "optimizer3 = Adam(lr=0.002)\r\n",
        "model_1.compile(loss='categorical_crossentropy', optimizer=optimizer1, metrics=['accuracy'])\r\n",
        "model_2.compile(loss='categorical_crossentropy', optimizer=optimizer2, metrics=['accuracy'])\r\n",
        "model_3.compile(loss='categorical_crossentropy', optimizer=optimizer3, metrics=['accuracy'])\r\n",
        "\r\n",
        "from tensorflow.keras.preprocessing.image import ImageDataGenerator\r\n",
        "\r\n",
        "datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)\r\n",
        "\r\n",
        "train_generator = datagen.flow_from_directory('/content/drive/My Drive/dirty_mnist_/dirty_mnist_2nd', target_size=(256,256), \r\n",
        "                  color_mode='grayscale', class_mode='categorical', subset='training')\r\n",
        "val_generator = datagen.flow_from_directory('/content/drive/My Drive/dirty_mnist_/dirty_mnist_2nd', target_size=(256,256), \r\n",
        "                  color_mode='grayscale', class_mode='categorical', subset='validation')\r\n",
        "from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau\r\n",
        "checkpoint_1 = ModelCheckpoint(f'/content/drive/My Drive/dirty_mnist_/checkpoint/checkpoint1_1.hdf5', \r\n",
        "monitor='val_accuracy', save_best_only=True, verbose=1)\r\n",
        "checkpoint_2 = ModelCheckpoint(f'/content/drive/My Drive/dirty_mnist_/checkpoint/checkpoint1_2.hdf5', \r\n",
        "monitor='val_accuracy', save_best_only=True, verbose=1)\r\n",
        "checkpoint_3 = ModelCheckpoint(f'/content/drive/My Drive/dirty_mnist_/checkpoint/checkpoint1_2.hdf5', \r\n",
        "monitor='val_accuracy', save_best_only=True, verbose=1)\r\n",
        "lr = ReduceLROnPlateau(patience=10,verbose=1,factor=0.5) #learning rate scheduler\r\n",
        "es = EarlyStopping(patience=30, verbose=1)\r\n",
        "hist1 = model_1.fit_generator(train_generator, epochs=100, validation_data=val_generator, callbacks=[checkpoint_1,lr,es])\r\n",
        "hist2 = model_2.fit_generator(train_generator, epochs=100, validation_data=val_generator, callbacks=[checkpoint_2,lr,es])\r\n",
        "hist3 = model_3.fit_generator(train_generator, epochs=100, validation_data=val_generator, callbacks=[checkpoint_3,lr,es])\r\n",
        "import matplotlib.pyplot as plt\r\n",
        "plt.plot(hist1.history[\"accuracy\"], label='m1_acc')\r\n",
        "plt.plot(hist1.history[\"val_accuracy\"], label='m1_vacc')\r\n",
        "plt.plot(hist2.history[\"accuracy\"], label='m2_acc')\r\n",
        "plt.plot(hist2.history[\"val_accuracy\"], label='m2_vacc')\r\n",
        "plt.plot(hist3.history[\"accuracy\"], label='m3_acc')\r\n",
        "plt.plot(hist3.history[\"val_accuracy\"], label='m3_acc')\r\n",
        "plt.legend()\r\n",
        "plt.show()\r\n",
        "'''\r\n",
        "from tensorflow.keras.models import load_model\r\n",
        "model_1 = load_model('c:/data/test/mnist/checkpoint/mnist_checkpoint7_1.hdf5', compile=False)\r\n",
        "model_2 = load_model('c:/data/test/mnist/checkpoint/mnist_checkpoint7_2.hdf5', compile=False)\r\n",
        "model_3 = load_model('c:/data/test/mnist/checkpoint/mnist_checkpoint7_3.hdf5', compile=False)\r\n",
        "\r\n",
        "\r\n",
        "# os.mkdir('../data/test/mnist/images_test/none')\r\n",
        "# import shutil\r\n",
        "# shutil.move(\"../data/test/mnist/images_test/*.png\", \"../data/test/mnist/images_test/none\")\r\n",
        "\r\n",
        "datagen = ImageDataGenerator(rescale=1./255)\r\n",
        "test_generator = datagen.flow_from_directory('../data/test/mnist/images_test', target_size=(256,256), \r\n",
        "color_mode='grayscale', class_mode='categorical', shuffle=False)\r\n",
        "\r\n",
        "predict_1 = model_1.predict_generator(test_generator).argmax(axis=1)\r\n",
        "predict_2 = model_2.predict_generator(test_generator).argmax(axis=1)\r\n",
        "predict_3 = model_3.predict_generator(test_generator).argmax(axis=1)\r\n",
        "\r\n",
        "submission[\"predict_1\"] = predict_1\r\n",
        "submission[\"predict_2\"] = predict_2\r\n",
        "submission[\"predict_3\"] = predict_3\r\n",
        "print(submission.head())\r\n",
        "\r\n",
        "from collections import Counter\r\n",
        "\r\n",
        "for i in range(len(submission)) :\r\n",
        "    predicts = submission.loc[i, ['predict_1','predict_2','predict_3']]\r\n",
        "    submission.at[i, \"digit\"] = Counter(predicts).most_common(n=1)[0][0]\r\n",
        "\r\n",
        "\r\n",
        "\r\n",
        "submission = submission[['id', 'digit']]\r\n",
        "temp = submission.copy()\r\n",
        "temp1 = temp['digit'].iloc[:7951]\r\n",
        "temp2 = temp['digit'].iloc[7951:]\r\n",
        "print(temp1.shape,temp2.shape)\r\n",
        "print(temp1)\r\n",
        "print(temp2)\r\n",
        "digit = pd.concat([temp2, temp1])\r\n",
        "print(digit)\r\n",
        "print(digit.shape)\r\n",
        "digit = np.array(digit)\r\n",
        "submission.loc[:,'digit'] = digit\r\n",
        "print(submission)\r\n",
        "submission.to_csv('../data/test/mnist/submission_ensemble3.csv', index=False)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4IfLA-BUwpSQ"
      },
      "source": [
        "import pandas as pd\r\n",
        "import numpy as np\r\n",
        "import matplotlib.pyplot as plt\r\n",
        "import cv2\r\n",
        "from tqdm import tqdm\r\n",
        "import imutils\r\n",
        "import zipfile\r\n",
        "import os\r\n",
        "from PIL import Image\r\n",
        "\r\n",
        "import torch\r\n",
        "import torch.nn as nn\r\n",
        "import torch.nn.functional as F\r\n",
        "import torchvision.models as models\r\n",
        "import torchvision.transforms as T\r\n",
        "from torch.utils.data import DataLoader, Dataset\r\n",
        "from google.colab import output\r\n",
        "\r\n",
        "dirty_mnist_answer = pd.read_csv(\"dirty_mnist_answer.csv\")\r\n",
        "# dirty_mnist라는 디렉터리 속에 들어있는 파일들의 이름을 \r\n",
        "# namelist라는 변수에 저장\r\n",
        "namelist = os.listdir('./dirty_mnist/')\r\n",
        "\r\n",
        "# unmpy를 tensor로 변환하는 ToTensor 정의\r\n",
        "class ToTensor(object):\r\n",
        "    \"\"\"numpy array를 tensor(torch)로 변환합니다.\"\"\"\r\n",
        "    def __call__(self, sample):\r\n",
        "        image, label = sample['image'], sample['label']\r\n",
        "        # swap color axis because\r\n",
        "        # numpy image: H x W x C\r\n",
        "        # torch image: C X H X W\r\n",
        "        image = image.transpose((2, 0, 1))\r\n",
        "        return {'image': torch.FloatTensor(image),\r\n",
        "                'label': torch.FloatTensor(label)}\r\n",
        "# to_tensor 선언\r\n",
        "to_tensor = T.Compose([\r\n",
        "                        ToTensor()\r\n",
        "                    ])\r\n",
        "\r\n",
        "class DatasetMNIST(torch.utils.data.Dataset):\r\n",
        "    def __init__(self,\r\n",
        "                 dir_path,\r\n",
        "                 meta_df,\r\n",
        "                 transforms=to_tensor,#미리 선언한 to_tensor를 transforms로 받음\r\n",
        "                 augmentations=None):\r\n",
        "        \r\n",
        "        self.dir_path = dir_path # 데이터의 이미지가 저장된 디렉터리 경로\r\n",
        "        self.meta_df = meta_df # 데이터의 인덱스와 정답지가 들어있는 DataFrame\r\n",
        "\r\n",
        "        self.transforms = transforms# Transform\r\n",
        "        self.augmentations = augmentations # Augmentation\r\n",
        "        \r\n",
        "    def __len__(self):\r\n",
        "        return len(self.meta_df)\r\n",
        "    \r\n",
        "    def __getitem__(self, index):\r\n",
        "        # 폴더 경로 + 이미지 이름 + .png => 파일의 경로\r\n",
        "        # 참고) \"12\".zfill(5) => 000012\r\n",
        "        #       \"146\".zfill(5) => 000145\r\n",
        "        # cv2.IMREAD_GRAYSCALE : png파일을 채널이 1개인 GRAYSCALE로 읽음\r\n",
        "        image = cv2.imread(self.dir_path +\\\r\n",
        "                           str(self.meta_df.iloc[index,0]).zfill(5) + '.png',\r\n",
        "                           cv2.IMREAD_GRAYSCALE)\r\n",
        "        # 0 ~ 255의 값을 갖고 크기가 (256,256)인 numpy array를\r\n",
        "        # 0 ~ 1 사이의 실수를 갖고 크기가 (256,256,1)인 numpy array로 변환\r\n",
        "        image = (image/255).astype('float')[..., np.newaxis]\r\n",
        "\r\n",
        "        # 정답 numpy array생성(존재하면 1 없으면 0)\r\n",
        "        label = self.meta_df.iloc[index, 1:].values.astype('float')\r\n",
        "        sample = {'image': image, 'label': label}\r\n",
        "\r\n",
        "        # transform 적용\r\n",
        "        # numpy to tensor\r\n",
        "        if self.transforms:\r\n",
        "            sample = self.transforms(sample)\r\n",
        "\r\n",
        "        # sample 반환\r\n",
        "        return sample\r\n",
        "\r\n",
        "# nn.Module을 상속 받아 MultiLabelResnet를 정의\r\n",
        "class MultiLabelResnet(nn.Module):\r\n",
        "    def __init__(self):\r\n",
        "        super(MultiLabelResnet, self).__init__()\r\n",
        "        self.conv2d = nn.Conv2d(1, 3, 3, stride=1)\r\n",
        "        self.resnet = models.resnet18() \r\n",
        "        self.FC = nn.Linear(1000, 26)\r\n",
        "\r\n",
        "    def forward(self, x):\r\n",
        "        # resnet의 입력은 [3, N, N]으로\r\n",
        "        # 3개의 채널을 갖기 때문에\r\n",
        "        # resnet 입력 전에 conv2d를 한 층 추가\r\n",
        "        x = F.relu(self.conv2d(x))\r\n",
        "\r\n",
        "        # resnet18을 추가\r\n",
        "        x = F.relu(self.resnet(x))\r\n",
        "\r\n",
        "        # 마지막 출력에 nn.Linear를 추가\r\n",
        "        # multilabel을 예측해야 하기 때문에\r\n",
        "        # softmax가 아닌 sigmoid를 적용\r\n",
        "        x = torch.sigmoid(self.FC(x))\r\n",
        "        return x\r\n",
        "# 모델 선언\r\n",
        "model = MultiLabelResnet()\r\n",
        "\r\n",
        "# cross validation을 적용하기 위해 KFold 생성\r\n",
        "from sklearn.model_selection import KFold\r\n",
        "kfold = KFold(n_splits=5, shuffle=True, random_state=0)\r\n",
        "\r\n",
        "# dirty_mnist_answer에서 train_idx와 val_idx를 생성\r\n",
        "best_models = [] # 폴드별로 가장 validation acc가 높은 모델 저장\r\n",
        "for fold_index, (trn_idx, val_idx) in enumerate(kfold.split(dirty_mnist_answer),1):\r\n",
        "    print(f'[fold: {fold_index}]')\r\n",
        "    # cuda cache 초기화\r\n",
        "    torch.cuda.empty_cache()\r\n",
        "\r\n",
        "    #train fold, validation fold 분할\r\n",
        "    train_answer = dirty_mnist_answer.iloc[trn_idx]\r\n",
        "    test_answer  = dirty_mnist_answer.iloc[val_idx]\r\n",
        "\r\n",
        "    #Dataset 정의\r\n",
        "    train_dataset = DatasetMNIST(\"dirty_mnist/\", train_answer)\r\n",
        "    valid_dataset = DatasetMNIST(\"dirty_mnist/\", test_answer)\r\n",
        "\r\n",
        "    #DataLoader 정의\r\n",
        "    train_data_loader = DataLoader(\r\n",
        "        train_dataset,\r\n",
        "        batch_size = 128,\r\n",
        "        shuffle = False,\r\n",
        "        num_workers = 3\r\n",
        "    )\r\n",
        "    valid_data_loader = DataLoader(\r\n",
        "        valid_dataset,\r\n",
        "        batch_size = 32,\r\n",
        "        shuffle = False,\r\n",
        "        num_workers = 3\r\n",
        "    )\r\n",
        "\r\n",
        "    # 모델 선언\r\n",
        "    model = MultiLabelResnet()\r\n",
        "    model.to(device)# gpu에 모델 할당\r\n",
        "\r\n",
        "    # 훈련 옵션 설정\r\n",
        "    optimizer = torch.optim.Adam(model.parameters(),\r\n",
        "                                lr = 0.001)\r\n",
        "    lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer,\r\n",
        "                                                step_size = 5,\r\n",
        "                                                gamma = 0.75)\r\n",
        "    criterion = torch.nn.BCELoss()\r\n",
        "\r\n",
        "    # 훈련 시작\r\n",
        "    valid_acc_max = 0\r\n",
        "    for epoch in range(10):\r\n",
        "        # 1개 epoch 훈련\r\n",
        "        train_acc_list = []\r\n",
        "        with tqdm(train_data_loader,#train_data_loader를 iterative하게 반환\r\n",
        "                total=train_data_loader.__len__(), # train_data_loader의 크기\r\n",
        "                unit=\"batch\") as train_bar:# 한번 반환하는 smaple의 단위는 \"batch\"\r\n",
        "            for sample in train_bar:\r\n",
        "                train_bar.set_description(f\"Train Epoch {epoch}\")\r\n",
        "                # 갱신할 변수들에 대한 모든 변화도를 0으로 초기화\r\n",
        "                # 참고)https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html\r\n",
        "                optimizer.zero_grad()\r\n",
        "                images, labels = sample['image'], sample['label']\r\n",
        "                # tensor를 gpu에 올리기 \r\n",
        "                images = images.to(device)\r\n",
        "                labels = labels.to(device)\r\n",
        "\r\n",
        "                # 모델의 dropoupt, batchnormalization를 train 모드로 설정\r\n",
        "                model.train()\r\n",
        "                # .forward()에서 중간 노드의 gradient를 계산\r\n",
        "                with torch.set_grad_enabled(True):\r\n",
        "                    # 모델 예측\r\n",
        "                    probs  = model(images)\r\n",
        "                    # loss 계산\r\n",
        "                    loss = criterion(probs, labels)\r\n",
        "                    # 중간 노드의 gradient로\r\n",
        "                    # backpropagation을 적용하여\r\n",
        "                    # gradient 계산\r\n",
        "                    loss.backward()\r\n",
        "                    # weight 갱신\r\n",
        "                    optimizer.step()\r\n",
        "\r\n",
        "                    # train accuracy 계산\r\n",
        "                    probs  = probs.cpu().detach().numpy()\r\n",
        "                    labels = labels.cpu().detach().numpy()\r\n",
        "                    preds = probs > 0.5\r\n",
        "                    batch_acc = (labels == preds).mean()\r\n",
        "                    train_acc_list.append(batch_acc)\r\n",
        "                    train_acc = np.mean(train_acc_list)\r\n",
        "\r\n",
        "                # 현재 progress bar에 현재 미니배치의 loss 결과 출력\r\n",
        "                train_bar.set_postfix(train_loss= loss.item(),\r\n",
        "                                      train_acc = train_acc)\r\n",
        "                \r\n",
        "\r\n",
        "        # 1개 epoch학습 후 Validation 점수 계산\r\n",
        "        valid_acc_list = []\r\n",
        "        with tqdm(valid_data_loader,\r\n",
        "                total=valid_data_loader.__len__(),\r\n",
        "                unit=\"batch\") as valid_bar:\r\n",
        "            for sample in valid_bar:\r\n",
        "                valid_bar.set_description(f\"Valid Epoch {epoch}\")\r\n",
        "                optimizer.zero_grad()\r\n",
        "                images, labels = sample['image'], sample['label']\r\n",
        "                images = images.to(device)\r\n",
        "                labels = labels.to(device)\r\n",
        "\r\n",
        "                # 모델의 dropoupt, batchnormalization를 eval모드로 설정\r\n",
        "                model.eval()\r\n",
        "                # .forward()에서 중간 노드의 gradient를 계산\r\n",
        "                with torch.no_grad():\r\n",
        "                    # validation loss만을 계산\r\n",
        "                    probs  = model(images)\r\n",
        "                    valid_loss = criterion(probs, labels)\r\n",
        "\r\n",
        "                    # train accuracy 계산\r\n",
        "                    probs  = probs.cpu().detach().numpy()\r\n",
        "                    labels = labels.cpu().detach().numpy()\r\n",
        "                    preds = probs > 0.5\r\n",
        "                    batch_acc = (labels == preds).mean()\r\n",
        "                    valid_acc_list.append(batch_acc)\r\n",
        "\r\n",
        "                valid_acc = np.mean(valid_acc_list)\r\n",
        "                valid_bar.set_postfix(valid_loss = valid_loss.item(),\r\n",
        "                                      valid_acc = valid_acc)\r\n",
        "            \r\n",
        "        # Learning rate 조절\r\n",
        "        lr_scheduler.step()\r\n",
        "\r\n",
        "        # 모델 저장\r\n",
        "        if valid_acc_max < valid_acc:\r\n",
        "            valid_acc_max = valid_acc\r\n",
        "            best_model = model\r\n",
        "            MODEL = \"resnet18\"\r\n",
        "            # 모델을 저장할 구글 드라이브 경로\r\n",
        "            path = \"/content/drive/MyDrive/월간데이콘 12/notebook/models/\"\r\n",
        "            torch.save(best_model, f'{path}{fold_index}_{MODEL}_{valid_loss.item():2.4f}_epoch_{epoch}.pth')\r\n",
        "\r\n",
        "    # 폴드별로 가장 좋은 모델 저장\r\n",
        "    best_models.append(best_model)\r\n",
        "\r\n",
        "# gpu에 올라가 있는 tensor -> cpu로 이동 -> numpy array로 변환\r\n",
        "sample_images = images.cpu().detach().numpy()\r\n",
        "sample_prob = probs\r\n",
        "sample_labels = labels\r\n",
        "\r\n",
        "idx = 1\r\n",
        "plt.imshow(sample_images[idx][0])\r\n",
        "plt.title(\"sample input image\")\r\n",
        "plt.show()\r\n",
        "\r\n",
        "print('예측값 : ',dirty_mnist_answer.columns[1:][sample_prob[idx] > 0.5])\r\n",
        "print('정답값 : ', dirty_mnist_answer.columns[1:][sample_labels[idx] > 0.5])\r\n",
        "\r\n",
        "#test Dataset 정의\r\n",
        "sample_submission = pd.read_csv(\"sample_submission.csv\")\r\n",
        "test_dataset = DatasetMNIST(\"test_dirty_mnist/\", sample_submission)\r\n",
        "batch_size = 128\r\n",
        "test_data_loader = DataLoader(\r\n",
        "    test_dataset,\r\n",
        "    batch_size = batch_size,\r\n",
        "    shuffle = False,\r\n",
        "    num_workers = 3,\r\n",
        "    drop_last = False\r\n",
        ")\r\n",
        "\r\n",
        "predictions_list = []\r\n",
        "# 배치 단위로 추론\r\n",
        "prediction_df = pd.read_csv(\"sample_submission.csv\")\r\n",
        "\r\n",
        "# 5개의 fold마다 가장 좋은 모델을 이용하여 예측\r\n",
        "for model in best_models:\r\n",
        "    # 0으로 채워진 array 생성\r\n",
        "    prediction_array = np.zeros([prediction_df.shape[0],\r\n",
        "                                 prediction_df.shape[1] -1])\r\n",
        "    for idx, sample in enumerate(test_data_loader):\r\n",
        "        with torch.no_grad():\r\n",
        "            # 추론\r\n",
        "            model.eval()\r\n",
        "            images = sample['image']\r\n",
        "            images = images.to(device)\r\n",
        "            probs  = model(images)\r\n",
        "            probs = probs.cpu().detach().numpy()\r\n",
        "            preds = (probs > 0.5)\r\n",
        "\r\n",
        "            # 예측 결과를 \r\n",
        "            # prediction_array에 입력\r\n",
        "            batch_index = batch_size * idx\r\n",
        "            prediction_array[batch_index: batch_index + images.shape[0],:]\\\r\n",
        "                         = preds.astype(int)\r\n",
        "                         \r\n",
        "    # 채널을 하나 추가하여 list에 append\r\n",
        "    predictions_list.append(prediction_array[...,np.newaxis])\r\n",
        "\r\n",
        "# axis = 2를 기준으로 평균\r\n",
        "predictions_array = np.concatenate(predictions_list, axis = 2)\r\n",
        "predictions_mean = predictions_array.mean(axis = 2)\r\n",
        "\r\n",
        "# 평균 값이 0.5보다 클 경우 1 작으면 0\r\n",
        "predictions_mean = (predictions_mean > 0.5) * 1\r\n",
        "predictions_mean\r\n",
        "\r\n",
        "sample_submission = pd.read_csv(\"sample_submission.csv\")\r\n",
        "sample_submission.iloc[:,1:] = predictions_mean\r\n",
        "sample_submission.to_csv(\"baseline_prediction.csv\", index = False)\r\n",
        "sample_submission\r\n",
        "\r\n"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}