SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID is NULL
ORDER BY OUTS.ANIMAL_ID


-- OUTS와 INS를 변수명으로 설정 각각 FROM JOIN 에서 설정

-- OUT.ANIMAL_ID 이런 식으로 표시한다

-- LEFT OUTER JOIN ANIMAL_INS INS -> ANIMAL_INS를 INS로 표시하고 JOIN함

-- ON OUTS.ANIMAL_ID = INS.ANIMAL_ID -> 공통부분을 결정하여 정렬시켜줌

