-- SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
-- FROM ANIMAL_OUTS
-- GROUP BY HOUR(DATETIME)
-- HAVING HOUR >= 9 AND HOUR < 20
-- ORDER BY HOUR(DATETIME)

SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19
GROUP BY HOUR(DATETIME)